#!/usr/bin/env bash

set -eu

BREW_PACKAGES=(
    bash
    bash-completion
    gawk
    gettext
    gnu-getopt
    gnu-indent
    gnu-sed
    gnu-tar
    ghostty
    grep
    micro
    shellcheck
    shfmt
    starship
    rcm
    util-linux
)

brew install "${BREW_PACKAGES[@]}"
